name: Deploy to Docker Host

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        run: |
          docker build --progress=plain -t ${{ secrets.DOCKER_USERNAME }}/miwebapp-imagen:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/miwebapp-imagen:latest
          
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose -f docker-compose.yml pull web #  Descarga la imagen de tu app
            DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}" SA_PASSWORD="${{ secrets.SA_PASSWORD }}" docker-compose -f docker-compose.yml run migrations
            docker-compose -f docker-compose.yml up -d  # Inicia o actualiza los contenedores